config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  resources :surveys do
    # resources :questions
  end
end

app/models/numerical_option.rb
class NumericalOption < ActiveRecord::Base
  has_many :option_options, as: :option
  has_many :questions, through: :option_options
end

app/models/open_option.rb
class OpenOption < ActiveRecord::Base
  has_many :option_options, as: :option
  has_many :questions, through: :option_options
end

app/models/option_option.rb
class OptionOption < ActiveRecord::Base
  belongs_to :option, polymorphic: true
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :option_options
  has_many :open_options, through: :option_options, source: :option, source_type: 'OpenOption'
  has_many :numerical_options, through: :option_options, source: :option, source_type: 'NumericalOption'

  validates :question_text, presence: true
  validates :question_position, presence: true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions

  validates :name, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @survey = Survey.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.container
  %h1 QB Tests
  #survey-area
    =link_to new_survey_path, id: "new-survey-link", class: "btn btn-success", remote: true do
      Create Survey

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questions Box Test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/surveys/_survey_start.html.haml
.container
  %h4 New Survey
  = form_for @survey, remote: true do |f|
    .form-group
      = f.label :name, "Survey Title", class: "pull-left"
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :body, "Optional Description / Disclaimer", class: "pull-left"
      = f.text_area :body, rows: "5", class: "form-control"
    %p.button
      = f.submit 'Submit', class: "btn btn-default"

app/views/surveys/new.js.erb
$('#new-survey-link').hide()
$('#survey-area').prepend("<%= j render 'survey_start' %>")